### ISSUE TITLE
issues when i try to use this demo

### ISSUE THREAD

**Issue by zpqi** [Victor-Morvy/btOsgQt#1]
C:\Users\zpq\Desktop\bullet example\can run\build-carControl-Desktop_Qt_5_9_7_MSVC2017_64bit-Debug\ui_mainwindow.h:22: error: C1083: cannot open file: “qtosgwidget.h”: No such file or directory

**Comment by Victor-Morvy** [comment]
sorry for being late, try to open mainWindow.ui in vim and change all "qtosgwidget" to "QtOSGWidget", i didn't test it yet, but it will works, i'll commit this new version quickly as possible.

**Comment by zpqi** [comment]
thanks for replying！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Victor-Morvy/btOsgQt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月13日(星期天) 晚上7:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Victor-Morvy/btOsgQt] issues when i try to use this demo (Issue #1)





 
sorry for being late, try to open mainWindow.ui in vim and change all "qtosgwidget" to "QtOSGWidget", i didn't test it yet, but it will works, i'll commit this new version quickly as possible.
